account/urls.py
from django.urls import  path , re_path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.RegisterView.as_view() , name='user_register'),
    path('login/', views.LoginView.as_view() , name='user_login'),
    path('logout/', views.LogoutView.as_view() , name='user_logout'),
    path('profile/', views.EditProfileView.as_view() , name='user_profile'),
    path('forget_password/', views.ForgetPasswordView.as_view(), name="forget_password"),
    path('reset_password/<uidb64>/<token>/', views.ResetPasswordView.as_view(), name="reset_password_form"),
]

blog/urls.py
from django.urls import path , re_path
from .views import BlogView, PostDetailView ,LikePostView , CommentReplyView

app_name ='blog'
urlpatterns = [
    path('blog/',BlogView.as_view(), name='blog'),
    re_path(r'^post-detail/(?P<slug>[-\wآ-ی]+)/(?P<id>\d+)/$', PostDetailView.as_view(), name='post_detail'),
    re_path(r'^like/(?P<slug>[-\wآ-ی]+)/(?P<id>\d+)/$', LikePostView.as_view(), name='post_like'),
    path('reply/<int:post_id>/<int:comment_id>/' , CommentReplyView.as_view() , name="reply_comment")

   
]

dashboard/urls.py
from django.urls import path , include
from . import views

app_name = 'dashboard'
home_urls = [

    path('about-us/edit/',views.AboutUsUpdateView.as_view(),name="edit_about"),

    path('service/list/',views.ServiceListView.as_view(),name="service_list"),
    path('service/create/',views.ServiceCreateView.as_view(),name="service_create"),
    path('service/delete/<int:pk>/',views.ServiceDeleteView.as_view(),name="service_delete"),
    path('service/update/<int:pk>/',views.ServiceUpdateView.as_view(),name="service_update"),

    path('stats-section/list/', views.StatsSectionListView.as_view(),name='stats_list'),
    path('stats-section/create/', views.StatsSectionCreateView.as_view(),name='stats_create'),
    path('stats-section/delete/<int:pk>/', views.StatsSectionDeleteView.as_view(),name='stats_delete'),
    path('stats-section/update/<int:pk>/', views.StatsSectionUpdateView.as_view(),name='stats_update'),

    path('portfolio_list/',views.PortfolioListView.as_view(),name = 'portfolio_list'),
    path('portfolio/create/',views.PortfolioCreateView.as_view(),name = 'portfolio_create'),
    path('portfolio/delete/<int:pk>/',views.PortfolioDeleteView.as_view(),name = 'portfolio_delete'),
    path('portfolio/update/<int:pk>/',views.PortfolioUpdateView.as_view(),name = 'portfolio_update'),

    path('portfolio_category_list/',views.PortfolioCategoryListView.as_view(), name = 'portfolio_category_list'),
    path('portfolio_category_create/',views.PortfolioCategoryCreateView.as_view(), name = 'portfolio_category_create'),
    path('portfolio_category_delete/<int:pk>/',views.PortfolioCategoryDeleteView.as_view(), name = 'portfolio_category_delete'),
    path('portfolio_category_update/<int:pk>/',views.PortfolioCategoryUpdateView.as_view(), name = 'portfolio_category_update'),

    
    path('team_list/',views.TeamMemberListView.as_view(), name = 'team_list'),
    path('team_create/',views.TeamMemberCreateView.as_view(), name = 'team_create'),
    path('team_delete/<int:pk>/',views.TeamMemberDeleteView.as_view(), name = 'team_delete'),
    path('team_update/<int:pk>/',views.TeamMemberUpdateView.as_view(), name = 'team_update'),

    
    path('contact_list/',views.ContactListView.as_view(), name='contact_list'),
    path('contact_reply/<int:pk>/',views.ContactReplyView.as_view(), name='contact_reply'),
    path('contact_delete/<int:pk>/',views.ContactDeleteView.as_view(), name='contact_delete'),

    
]
blog_urls = [
    path('post/list/',views.PostListView.as_view(),name="post_list"),
    path('post/create/',views.PostCreateView.as_view(),name="post_create"),
    path('post/delete/<int:pk>/',views.PostDeleteView.as_view(),name="post_delete"),
    path('post/update/<int:pk>/',views.PostUpdateView.as_view(),name="post_update"),


    path('comment/list/',views.CommentListView.as_view(), name="comment_list"),
    path('comment/delete/<int:pk>/',views.CommentDeleteView.as_view(), name="comment_delete"),
    path('comment/reply/<int:comment_id>/',views.CommentReplyView.as_view(), name="comment_reply"),
    path('comment/detail/<int:comment_id>/',views.CommentDetailView.as_view(), name="comment_detail"),
   
]

urlpatterns = [

    path('home/app/', include(home_urls)),
    path('blog/app/', include(blog_urls)),
    path('admin/profile/',views.AdminProfileView.as_view(),name = 'admin_profile'),
    path('users/list/',views.UserListView.as_view(),name='user_list'),
    path('user/create/', views.UserCreateView.as_view(),name='user_create'),
    path('user/delete/<int:pk>/', views.UserDeleteView.as_view(),name='user_delete'),
    path('user/update/<int:pk>/', views.UserUpdateView.as_view(),name='user_update'),
    path('',views.DashboardView.as_view(),name="dashboard"),

]

home/urls.py
from django.urls import path , re_path
from .views import HomeView , ContactView, PortfolioDetailView 

app_name = 'home'

urlpatterns = [
    
    path('contact/', ContactView.as_view(), name='contact'),
    re_path(r'^(?P<cat_slug>[-\wآ-ی]+)/$', HomeView.as_view() , name='home'),
    re_path(r'^portfolio/(?P<port_slug>[-\wآ-ی]+)/$', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('', HomeView.as_view() , name='home'),

]

meta/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/' , include('account.urls',namespace ='account')),
    path('dashboard/' , include('dashboard.urls',namespace ='dashboard')),
       path('' , include('blog.urls',namespace = 'blog')),
    path('', include('home.urls' , namespace='home')),
 

]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/massages.html
{% if messages %}

    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}" >{{msg}}</p>
    {% endfor %}


{% endif %}

templates/include/nav.html
       <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <!-- LOGO -->
                <a class="navbar-brand logo" href="{% url 'home:home' %}">
                   الی سایفر
                </a>

                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto">
                        <!--Nav Links-->
                        <li class="nav-item">
                            <a href="#" class="nav-link active" data-scroll-nav="0" >خانه</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-scroll-nav="1" >درباره ما</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-scroll-nav="2" >سرویس ها</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-scroll-nav="3">نمونه کارها</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-scroll-nav="4">وبلاگ</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link" data-scroll-nav="5">تماس با من</a>
                        </li>
                        {% if request.user.is_admin %}
                        <li class="nav-item">
                            <a href="{% url 'dashboard:dashboard' %}" class="nav-link" >داشبورد</a>
                        </li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'account:user_profile' %}" class="nav-link" >پروفایل</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'account:user_logout' %}" class="nav-link" >خروج</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'account:user_register' %}" class="nav-link" >ورود / عضویت</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            {% include 'include/massages.html' %}
        </nav>