blog/urls.py
from django.urls import path , re_path
from .views import BlogView, PostDetailView ,LikePostView , CommentReplyView

app_name ='blog'
urlpatterns = [
    path('blog/',BlogView.as_view(), name='blog'),
    re_path(r'^post-detail/(?P<slug>[-\wآ-ی]+)/(?P<id>\d+)/$', PostDetailView.as_view(), name='post_detail'),
    re_path(r'^like/(?P<slug>[-\wآ-ی]+)/(?P<id>\d+)/$', LikePostView.as_view(), name='post_like'),
    path('reply/<int:post_id>/<int:comment_id>/' , CommentReplyView.as_view() , name="reply_comment")

   
]

dashboard/urls.py
from django.urls import path , include
from . import views

app_name = 'dashboard'
home_urls = [

    path('about-us/edit/',views.AboutUsUpdateView.as_view(),name="edit_about"),

    path('service/list/',views.ServiceListView.as_view(),name="service_list"),
    path('service/create/',views.ServiceCreateView.as_view(),name="service_create"),
    path('service/delete/<int:pk>/',views.ServiceDeleteView.as_view(),name="service_delete"),
    path('service/update/<int:pk>/',views.ServiceUpdateView.as_view(),name="service_update"),

    path('stats-section/list/', views.StatsSectionListView.as_view(),name='stats_list'),
    path('stats-section/create/', views.StatsSectionCreateView.as_view(),name='stats_create'),
    path('stats-section/delete/<int:pk>/', views.StatsSectionDeleteView.as_view(),name='stats_delete'),
    path('stats-section/update/<int:pk>/', views.StatsSectionUpdateView.as_view(),name='stats_update'),

    path('portfolio_list/',views.PortfolioListView.as_view(),name = 'portfolio_list'),
    path('portfolio/create/',views.PortfolioCreateView.as_view(),name = 'portfolio_create'),
    path('portfolio/delete/<int:pk>/',views.PortfolioDeleteView.as_view(),name = 'portfolio_delete'),
    path('portfolio/update/<int:pk>/',views.PortfolioUpdateView.as_view(),name = 'portfolio_update'),

    path('portfolio_category_list/',views.PortfolioCategoryListView.as_view(), name = 'portfolio_category_list'),
    path('portfolio_category_create/',views.PortfolioCategoryCreateView.as_view(), name = 'portfolio_category_create'),
    path('portfolio_category_delete/<int:pk>/',views.PortfolioCategoryDeleteView.as_view(), name = 'portfolio_category_delete'),
    path('portfolio_category_update/<int:pk>/',views.PortfolioCategoryUpdateView.as_view(), name = 'portfolio_category_update'),

    
    path('team_list/',views.TeamMemberListView.as_view(), name = 'team_list'),
    path('team_create/',views.TeamMemberCreateView.as_view(), name = 'team_create'),
    path('team_delete/<int:pk>/',views.TeamMemberDeleteView.as_view(), name = 'team_delete'),
    path('team_update/<int:pk>/',views.TeamMemberUpdateView.as_view(), name = 'team_update'),

    
    path('contact_list/',views.ContactListView.as_view(), name='contact_list'),
    path('contact_reply/<int:pk>/',views.ContactReplyView.as_view(), name='contact_reply'),
    path('contact_delete/<int:pk>/',views.ContactDeleteView.as_view(), name='contact_delete'),

    
]
blog_urls = [
    path('post/list/',views.PostListView.as_view(),name="post_list"),
    path('post/create/',views.PostCreateView.as_view(),name="post_create"),
    path('post/delete/<int:pk>/',views.PostDeleteView.as_view(),name="post_delete"),
    path('post/update/<int:pk>/',views.PostUpdateView.as_view(),name="post_update"),


    path('comment/list/',views.CommentListView.as_view(), name="comment_list"),
    path('comment/delete/<int:pk>/',views.CommentDeleteView.as_view(), name="comment_delete"),
    path('comment/reply/<int:comment_id>/',views.CommentReplyView.as_view(), name="comment_reply"),
    path('comment/detail/<int:comment_id>/',views.CommentDetailView.as_view(), name="comment_detail"),
   
]

urlpatterns = [

    path('home/app/', include(home_urls)),
    path('blog/app/', include(blog_urls)),
    path('admin/profile/',views.AdminProfileView.as_view(),name = 'admin_profile'),
    path('users/list/',views.UserListView.as_view(),name='user_list'),
    path('user/create/', views.UserCreateView.as_view(),name='user_create'),
    path('user/delete/<int:pk>/', views.UserDeleteView.as_view(),name='user_delete'),
    path('user/update/<int:pk>/', views.UserUpdateView.as_view(),name='user_update'),
    path('',views.DashboardView.as_view(),name="dashboard"),

]

meta/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/' , include('account.urls',namespace ='account')),
    path('dashboard/' , include('dashboard.urls',namespace ='dashboard')),
       path('' , include('blog.urls',namespace = 'blog')),
    path('', include('home.urls' , namespace='home')),
 

]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.views import View
from home.models import AboutUs , Service , StatsSection , Portfolio  ,Category ,  TeamMember , Contact
from django.views.generic import CreateView , DeleteView , ListView , UpdateView 
from django.urls import reverse_lazy
from .mixins import CancelUrlMixin , SuperUserOnlyMixin , DeleteSuccessMessageMixin , SuccessMessageMixin
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from blog.models import Post  , Comment
from django.contrib import messages
from account.models import Member
from .forms import (
    AdminProfileForm,
    CommentConfirmeForm,
    CommentReplyForm,
    ContactForm,
    PortfolioForm,
    PostForm,
    SocialLinkFormSet,
    SocialTeamMemberFormset,
    UpdateUserForm,

)


# Create your views here.


class DashboardView(View):

    def get(self , request):
        return render(request , 'dashboard.html')
    
#AboutUs  ----------------------------------
class AboutUsUpdateView(UpdateView , SuccessMessageMixin ):
    model = AboutUs
    fields = '__all__'
    template_name = 'home-dashboard/aboutus_edit.html'
    success_url = reverse_lazy('dashboard:edit_about')

    def get_object(self, queryset=None):
        # همیشه فقط یک شیء رو برمی‌گردونه
        return AboutUs.objects.first()
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        formset = SocialLinkFormSet(instance=self.object)
        return render(request, self.template_name, {'form': form, 'formset': formset})
    
    def post(self , request , *args , **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        formset = SocialLinkFormSet(request.POST,instance=self.object)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form, 'formset': formset})
    


#Service  ------------------------------

class ServiceListView(ListView):
    model = Service
    template_name = 'home-dashboard/service_list.html'
    context_object_name = 'services'


class ServiceDeleteView(DeleteSuccessMessageMixin , DeleteView , CancelUrlMixin  ):
    model = Service
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:service_list")

  

class ServiceCreateView(SuccessMessageMixin ,CreateView):
    model = Service
    fields = '__all__'
    template_name = 'shared/create.html'
    success_url = reverse_lazy("dashboard:service_list")
    action = 'create'


 

class ServiceUpdateView(SuccessMessageMixin , UpdateView ):
    model = Service
    fields = '__all__'
    template_name = 'shared/update.html'
    success_url = reverse_lazy("dashboard:service_list")
    action = 'update'


#StatsSection  ----------------------------------
class StatsSectionListView(ListView):
    model = StatsSection
    template_name = 'home-dashboard/stats_list.html'
    context_object_name = 'statss'


class StatsSectionDeleteView(DeleteSuccessMessageMixin ,DeleteView , CancelUrlMixin ):
    model = StatsSection
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:stats_list")
  

class StatsSectionCreateView(SuccessMessageMixin , CreateView):
    action = 'create'
    model = StatsSection
    fields = '__all__'
    template_name = 'shared/create.html'
    success_url = reverse_lazy("dashboard:stats_list")

 

class StatsSectionUpdateView(SuccessMessageMixin ,UpdateView ):
    action = 'update'
    model = StatsSection
    fields = '__all__'
    template_name = 'shared/update.html'
    success_url = reverse_lazy("dashboard:stats_list")

#Portfolio  ----------------------------------
class PortfolioListView(ListView):
    model = Portfolio
    template_name = 'home-dashboard/portfolio_list.html'
    context_object_name = 'portfolios'

class PortfolioDeleteView(DeleteSuccessMessageMixin ,DeleteView , CancelUrlMixin ):
    model = Portfolio
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:portfolio_list")

class PortfolioCreateView(SuccessMessageMixin,CreateView):
    action = 'create'
    model = Portfolio
    form_class = PortfolioForm
    template_name = 'shared/create.html'
    success_url = reverse_lazy("dashboard:portfolio_list")

class PortfolioUpdateView(SuccessMessageMixin,UpdateView ):
    action = 'update'
    model = Portfolio
    form_class = PortfolioForm
    template_name = 'shared/update.html'
    success_url = reverse_lazy("dashboard:portfolio_list")

# Category Portfolio  ------------------------------
class PortfolioCategoryListView(ListView):
    model = Category
    template_name = 'home-dashboard/portfolio_category_list.html'
    context_object_name = 'categories'

class PortfolioCategoryDeleteView(DeleteSuccessMessageMixin,DeleteView , CancelUrlMixin ):
    model = Category
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:portfolio_category_list")

class PortfolioCategoryCreateView(SuccessMessageMixin,CreateView):
    action = 'create'
    model = Category
    fields = '__all__'
    template_name = 'shared/create.html'
    success_url = reverse_lazy("dashboard:portfolio_category_list")

class PortfolioCategoryUpdateView(SuccessMessageMixin,UpdateView ):
    action = 'update'
    model = Category
    fields = '__all__'
    template_name = 'shared/update.html'
    success_url = reverse_lazy("dashboard:portfolio_category_list")

# Team  ------------------------------

class TeamMemberListView(ListView , SuperUserOnlyMixin ):
    model = TeamMember
    template_name = 'home-dashboard/team_member/team_list.html'
    context_object_name = 'teams'

class TeamMemberDeleteView(DeleteSuccessMessageMixin,DeleteView , CancelUrlMixin , SuperUserOnlyMixin):
    model = TeamMember
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:team_list")

class TeamMemberCreateView(SuccessMessageMixin,CreateView , SuperUserOnlyMixin):
    model = TeamMember
    fields = '__all__'
    template_name = 'home-dashboard/team_member/team_create.html'
    success_url = reverse_lazy("dashboard:team_list")

    def get(self, request, *args, **kwargs):
        form = self.get_form()
        formset = SocialTeamMemberFormset()
        return render(request, self.template_name, {'form': form, 'formset': formset})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        formset = SocialTeamMemberFormset(request.POST)
        if form.is_valid() and formset.is_valid():
            team_member = form.save()
            formset.instance = team_member
            formset.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form, 'formset': formset})

class TeamMemberUpdateView(SuccessMessageMixin,UpdateView , SuperUserOnlyMixin ):
    model = TeamMember
    fields = '__all__'
    template_name = 'home-dashboard/team_member/team_update.html'
    success_url = reverse_lazy("dashboard:team_list")

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        formset = SocialTeamMemberFormset(instance=self.object)
        return render(request, self.template_name, {'form': form, 'formset': formset})
    
    def post(self , request , *args , **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        formset = SocialTeamMemberFormset(request.POST,instance=self.object)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form, 'formset': formset})

# Contact  ------------------------------

class ContactListView(ListView):
    model = Contact
    template_name = 'home-dashboard/contact/contact_list.html'
    context_object_name = 'contacts'

class ContactDeleteView(DeleteSuccessMessageMixin,DeleteView , CancelUrlMixin ):
    model = Contact
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:contact_list")

class ContactReplyView(UpdateView ):
    model = Contact
    form_class = ContactForm
    template_name = 'home-dashboard/contact/contact_reply.html'
    success_url = reverse_lazy("dashboard:contact_list")

    def form_valid(self , form):
        obj = form.save(commit=False)
        if 'reply' in form.changed_data and obj.reply :
            obj.replyed = True
            self.send_mail_to_user(obj)
        obj.save()
        return super().form_valid(form)

    def send_mail_to_user(request , contact):
    
        context = {
            'user_message': contact.message,
            'admin_response': contact.reply,

        }
        subject = 'پاسخ به پیام شما'
        from_email = settings.EMAIL_HOST_USER
        to_email = contact.email
        html_message = render_to_string('home-dashboard/contact/reply_email.html',context)
        plain_message = strip_tags(html_message)

        send_mail(subject ,plain_message, from_email , [to_email] ,html_message=html_message)

# Post --------------------------------------

class PostListView(ListView):
    model = Post
    template_name = 'blog-dashboard/post_list.html'
    context_object_name = 'posts'
    
class PostCreateView(SuccessMessageMixin,CreateView):
    model = Post
    form_class = PostForm
    template_name = 'shared/create.html'
    success_url = reverse_lazy("dashboard:post_list")


class PostDeleteView(DeleteSuccessMessageMixin,DeleteView):
    model = Post
    template_name = 'shared/delete.html'
    success_url = reverse_lazy("dashboard:post_list")

class PostUpdateView(SuccessMessageMixin,UpdateView):
    model = Post
    form_class = PostForm

dashboard/templates/home-dashboard/aboutus_edit.html
{% extends 'dashboard-base.html' %}
{% load widget_tweaks %}


{% block title %}
  <h1 class="title text-right">ویرایش درباره ما</h1> 
{% endblock %}

{% include 'include\massages.html' %}

{% block admin_content %}
<div class="container mt-4" style="direction: rtl; text-align: right;">
  <div class="card shadow-sm p-4">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}

      {% for field in form %}
        <div class="form-group mb-3">
          <label for="{{ field.id_for_label }}" class="form-label">
            {{ field.label }}
          </label>
        
          {{ field|add_class:"form-control" }}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <div class="text-danger small mt-1">
              {{ error }}
            </div>
          {% endfor %}
        </div>
      {% endfor %}
      {{ formset.management_form }}
    {% for subform in formset %}
      <div style="border:1px solid #ccc; padding:10px; margin-bottom:10px;">
        {{ subform.as_p }}
      </div>
    {% endfor %}

      <button type="submit" class="btn btn-primary mt-3">ذخیره</button>
    </form>
  </div>
</div>
{% endblock %}

dashboard/templates/home-dashboard/portfolio_category_list.html
{% extends 'dashboard-base.html' %}


 {% block title %}
    <h1 class="title">دسته بندی نمونه کارها</h1> 
 {% endblock %}

{% include 'include\massages.html' %}

{% block admin_content %}

<div style="direction: rtl; text-align: right; padding: 0 20px;">
<a href="{% url 'dashboard:portfolio_category_create' %}" class="btn btn-primary">ایجاد دسته بندی </a>

<br>
<br>
  <table class="table table-dark table-striped text-right">
      
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">عنوان</th>
      <th scope="col">آدرس دسته بندی</th>
    </tr>
  </thead>
  <tbody>
  {% for category in categories %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{category.title}}</td>
      <td>{{category.slug}}</td>
      <td class="fa fa-{{category.icon}}"></td>
      <td><a class="btn btn-danger" href="{% url 'dashboard:portfolio_category_delete' category.pk %}">حذف</a></td>
      <td><a  class="btn btn-warning" href="{% url 'dashboard:portfolio_category_update' category.pk %}">ویرایش</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  

{% endblock %}

dashboard/templates/home-dashboard/portfolio_list.html
{% extends 'dashboard-base.html' %}
{% load jalali_tags %}


 {% block title %}
    <h1 class="title">نمونه کار ها</h1> 
 {% endblock %}

{% include 'include\massages.html' %}

{% block admin_content %}

<div style="direction: rtl; text-align: right; padding: 0 20px;">
<a href="{% url 'dashboard:portfolio_create' %}" class="btn btn-primary">افزودن نمونه کار </a>

<br>
<br>
  <table class="table table-dark table-striped text-right">
      
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">عنوان</th>
      <th scope="col">آدرس نمونه کار</th>
      <th scope="col">کارفرما</th>
      <th scope="col">تاریخ ساخت</th>
      <th scope="col">آدرس پروژه</th>
      <th scope="col">توضیحات</th>
      <th scope="col">حذف</th>
      <th scope="col">ویرایش</th>
    </tr>
  </thead>
  <tbody>
  {% for portfolio in portfolios %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{portfolio.title}}</td>
      <td>{{portfolio.slug}}</td>
      <td>{{portfolio.employer}}</td>
      <td>{{portfolio.history|to_jalali}}</td>
      <td>{{portfolio.address_project}}</td>
      <td>{{portfolio.description|truncatechars:50}}</td>
      <td><a class="btn btn-danger" href="{% url 'dashboard:portfolio_delete' portfolio.pk %}">حذف</a></td>
      <td><a  class="btn btn-warning" href="{% url 'dashboard:portfolio_update' portfolio.pk %}">ویرایش</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  

{% endblock %}

dashboard/templates/home-dashboard/service_list.html
{% extends 'dashboard-base.html' %}


 {% block title %}
    <h1 class="title">سرویس ها</h1> 
 {% endblock %}

{% include 'include\massages.html' %}

{% block admin_content %}

<div style="direction: rtl; text-align: right; padding: 0 20px;">
<a href="{% url 'dashboard:service_create' %}" class="btn btn-primary">ایجاد سرویس </a>

<br>
<br>
  <table class="table table-dark table-striped text-right">
      
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">عنوان</th>
      <th scope="col">توضیحات</th>
      <th scope="col">آیکن</th>
    </tr>
  </thead>
  <tbody>
  {% for service in services %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{service.title}}</td>
      <td>{{service.description|truncatechars:50}}</td>
      <td class="fa fa-{{service.icon}}"></td>
      <td><a class="btn btn-danger" href="{% url 'dashboard:service_delete' service.pk %}">حذف</a></td>
      <td><a  class="btn btn-warning" href="{% url 'dashboard:service_update' service.pk %}">ویرایش</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  

{% endblock %}

dashboard/templates/home-dashboard/stats_list.html
{% extends 'dashboard-base.html' %}


 {% block title %}
    <h1 class="title">دستاورد ها</h1> 
 {% endblock %}

{% include 'include\massages.html' %}

{% block admin_content %}

<div style="direction: rtl; text-align: right; padding: 0 20px;">
<a href="{% url 'dashboard:stats_create' %}" class="btn btn-primary">ایجاد دستاورد </a>

<br>
<br>
  <table class="table table-dark table-striped text-right">
      
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">عنوان</th>
      <th scope="col">آیکن</th>
      <th scope="col">مقدار</th>
    </tr>
  </thead>
  <tbody>
  {% for stats in statss %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{stats.title}}</td>
      <td class="fa fa-{{stats.icon}}"></td>
      <td>{{stats.value}}</td>
      <td><a class="btn btn-danger" href="{% url 'dashboard:stats_delete' stats.pk %}">حذف</a></td>
      <td><a  class="btn btn-warning" href="{% url 'dashboard:stats_update' stats.pk %}">ویرایش</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  

{% endblock %}